<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.CloudGames.Application\Fiap.CloudGames.Application.csproj" />
    <ProjectReference Include="..\Fiap.CloudGames.Domain\Fiap.CloudGames.Domain.csproj" />
  </ItemGroup>

</Project>
